spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: Vynn
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


